sudo: required
services:
  - docker

before_install:
  - docker build -t fabis94/multi-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run fabis94/multi-react-test npm test -- --coverage

after_success:
  - docker build -t fabis94/multi-client ./client
  - docker build -t fabis94/multi-nginx ./nginx
  - docker build -t fabis94/multi-server ./server
  - docker build -t fabis94/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push fabis94/multi-client
  - docker push fabis94/multi-nginx
  - docker push fabis94/multi-server
  - docker push fabis94/multi-worker
